[tasks.ci]
run = [
  "pn fmt:check",
  "pn lint",
  "pn -r typecheck",
]

[tasks.docs]
run = "uvx zensical build --clean"

[env]
MISE_EXPERIMENTAL = 1

[tools]
node = "lts/krypton"
pnpm = "latest"
uv = "latest"

[deps.pnpm]
auto = true
